import turtle

turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.shape("turtle")
turtle.color("red")
turtle.color("red", "yellow")
turtle.hideturtle()
turtle.showturtle()
turtle.circle(100)
turtle.pencolor("blue")
turtle.right(45)
turtle.forward(100)
turtle.backward(200)
turtle.home()
turtle.clear()
turtle.done()
