import re

# m = re.match("a.c", "abc")
# print(m)
# print(m.group())

# m = re.match("a.c", "abbc")
# print(m)

# m = re.search("a.c", "test abc test")
# print(m)
# print(m.span())
# print(m.group())

# m = re.search("a.c", "test abc test adc")
# print(m)
# print(m.span())
# print(m.group())

# m = re.findall("a.c", "test abc test adc")
# print(m)

# m = re.finditer("a.c", "test abc test abc")
# print([w.group() for w in m])

m = re.match("ab?", "a")
print(m)
m = re.match("ab?", "ab")
print(m)
m = re.match("ab?", "abb")
print(m)

m = re.match("ab*", "a")
print(m)
m = re.match("ab*", "ab")
print(m)
m = re.match("ab*", "abb")
print(m)

m = re.match("ab+", "a")
print(m)
m = re.match("ab+", "ab")
print(m)
m = re.match("ab+", "abb")
print(m)

m = re.match("a{3}", "a")
print(m)
m = re.match("a{3}", "aaa")
print(m)
m = re.match("a{3}", "aaaa")
print(m)

m = re.match("a{3,5}", "a")
print(m)
m = re.match("a{3,5}", "aaaa")
print(m)
m = re.match("a{3,5}", "aaaaaaaa")
print(m)

m = re.match("[a-zA-Z0-9_]", "a")
print(m)
m = re.match("[a-zA-Z0-9_]", "A")
print(m)
m = re.match("[a-zA-Z0-9_]", "1")
print(m)
m = re.match("[a-zA-Z0-9_]", "@")
print(m)

m = re.match("[^a-zA-Z0-9_]", "a")
print(m)
m = re.match("[^a-zA-Z0-9_]", "@")
print(m)

m = re.match("\w", "a")
print(m)
m = re.match("\w", "@")
print(m)
m = re.match("\W", "a")
print(m)
m = re.match("\W", "@")
print(m)

m = re.match("\d", "1")
print(m)
m = re.match("\d", "a")
print(m)
m = re.match("\D", "1")
print(m)
m = re.match("\D", "a")
print(m)

m = re.match("a|b", "b")
print(m)
m = re.match("a|b", "x")
print(m)

m = re.match("(abc)+", "abc")
print(m)
m = re.match("(abc)+", "abcabc")
print(m)
m = re.match("(abc)+", "abcabcabc")
print(m)

m = re.match("\s", " ")
print(m)
m = re.match("\s", "a")
print(m)
m = re.match("\S", " ")
print(m)
m = re.match("\S", "a")
print(m)

m = re.match("\?", "?")
print(m)
m = re.match("\*", "*")
print(m)

m = re.search("^abc", "abc test abc")
print(m)
m = re.search("^abc", "test abc test abc")
print(m)
m = re.search("abc$", "test abc test abc")
print(m)
m = re.search("abc$", "test abc test")
print(m)
