s = "{}, {}, {}".format('a', 'b', 'c')
print(s)
s = "{0}, {1}, {2}".format('a', 'b', 'c')
print(s)
s = "{2}, {1}, {0}".format('a', 'b', 'c')
print(s)

s = "{name} {family}".format(name='taro', family='yamada')
print(s)

t = (1, 2, 3)
s = "{0[0]}, {0[1]}, {0[2]}".format(t)
print(s)
s = "{t[0]}, {t[1]}, {t[2]}".format(t=t)
print(s)
s = "{0}, {1}, {2}".format(*t)
print(s)
s = "{0}, {1}, {2}".format(t[0], t[1], t[2])
print(s)

d = {'name': 'taro', 'family': 'yamada'}
s = "{0[name]} {0[family]}".format(d)
print(s)
s = "{name} {family}".format(**d)
print(s)
s = "{d[name]} {d[family]}".format(d=d)
print(s)

s = "{:<30}".format("left")
print(s)
s = "{:>30}".format("right")
print(s)
s = "{:^30}".format("center")
print(s)
s = "{:*^30}".format("center")
print(s)
s = "{0:*^30}".format("center")
print(s)
s = "{name:*^30}".format(name="center")
print(s)
s = "{name:{fill}{align}{width}}".format(name="center", fill="*", align="^", width="30")
print(s)

s = "{:,}".format(1234567890)
print(s)
s = "{:_}".format(1234567890)
print(s)
s = "{:+f} {:+f}".format(3.14, -3.14)
print(s)
s = "{:-f} {:-f}".format(3.14, -3.14)
print(s)
s = "{:f} {:f}".format(3.14, -3.14)
print(s)

s = "{}".format(19/22)
print(s)
s = "{:.2%}".format(19/22)
print(s)

print(int(100), hex(100), oct(100), bin(100))
print("{0:d} {0:x} {0:o} {0:b}".format(100))

for i in range(20):
    for base in "bdX":
        print("{0:{width}{base}}".format(i, base=base, width=5), end=" ")
    print()
